POST /api/2.3/tenders/29799dd727db4e518cbc6ea78f3d3c5e/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1090
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/a1b5ec0fc2714a65b6540f68ec01f392?KeyID=feefed29&Signature=rYalRXL44gpfw6%2F9wY6JGQ8sGLCdioyYqKd4x4TtF7FvwFyfwwlRjIfh8mjVuFm%2BpQK4cXvqrWK4Y0QuXDI6Cw%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/29799dd727db4e518cbc6ea78f3d3c5e/bids/477bb612a31a4543adbafa436de38a9c
{
  "access": {
    "token": "c9fa58ae9a6c44a4a6fba092363cbac1"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/29799dd727db4e518cbc6ea78f3d3c5e/bids/477bb612a31a4543adbafa436de38a9c/documents/b23f5b25bec1404c905b57a107c12e63?download=a1b5ec0fc2714a65b6540f68ec01f392", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-23T18:57:45.796308+02:00", 
        "id": "b23f5b25bec1404c905b57a107c12e63", 
        "dateModified": "2016-12-23T18:57:45.796351+02:00"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "477bb612a31a4543adbafa436de38a9c", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2016-12-23T18:57:45.795279+02:00", 
    "selfQualified": true
  }
}

